# Generated by Django 4.1.7 on 2023-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentgroup_delete_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='student_names',
            new_name='students',
        ),
    ]
