name: sample-workflow
on: 
    push:
        branches:
            - main
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print-greeting
              run: |
                echo "Hello World"
                echo "Hello World2"