name: sample-workflow
on: 
    push:
        branches:
            - main
            - master
    workflow_dispatch:
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: get code #download the code
              uses: actions/checkout@v3 #added a comment